### PR TITLE
Fix trip delays

### LINKED ISSUE #575: Double Minus and Wrong Color of Negative Delay
There should only be one minus and it should be green. The color is correct in the TripDetails screen.

screenshot_20190124-172914_transportr_devel

### PR DESCRIPTION
**Pull request by ialokim**
This PR unifies the delay handling for `trips.search` with `trips.detail` and by doing so applies the right color to trips with "negative delay" (so public transport services ahead of their time). It also fixes the bug to not display a double minus in front of such delays.

The second commit just moves `BaseViewHolder` to the `trips` package as it is now used by both subpackages.

Fixes #575

### CODE REVIEW

File: app/src/main/java/de/grobox/transportr/utils/DateUtils.java [hunk 1]
```diff
@@ -83,13 +83,7 @@ public static String getDelayString(long delay) {
...
 	@Nullable
 	public static String getDelayText(long delay) {
-		if (delay >= 0) {
-			return "+" + Long.toString(delay / 1000 / 60);
-		} else if (delay < 0) {
-			return "-" + Long.toString(delay / 1000 / 60);
-		} else {
-			return null;
-		}
+		return (delay >= 0 ? "+" : "") + Long.toString(delay / 1000 / 60);
```
Comment (grote) [inline app/src/main/java/de/grobox/transportr/utils/DateUtils.java]: I think this isn't `@Nullable` anymore, right? Could you please remove the annotation and check all usages of this function please and remove `null` handling there?

File: app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt [hunk 2]
```diff
@@ -33,20 +33,20 @@ import de.schildbach.pte.dto.Position
...
+internal abstract class BaseViewHolder(v: View) : RecyclerView.ViewHolder(v) {
 
     protected val context: Context = v.context
     protected val fromTime: TextView = v.findViewById(R.id.fromTime)
     protected val toTime: TextView = v.findViewById(R.id.toTime)
     protected val fromDelay: TextView = v.findViewById(R.id.fromDelay)
     protected val toDelay: TextView = v.findViewById(R.id.toDelay)
 
-    fun setArrivalTimes(timeView: TextView, delayView: TextView, stop: Stop) {
+    fun setArrivalTimes(timeView: TextView?, delayView: TextView, stop: Stop, showZeroDelay: Boolean = true) {
```
Comment (grote) [inline app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt]: Why do we need `showZeroDelay`? I think the convention was (or should be) to show a green +0 if real time information is available and to show nothing if it isn't available.

File: app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt [hunk 3]
```diff
@@ -26,12 +26,13 @@ import android.view.View.VISIBLE
...
 import android.widget.ImageView
 import android.widget.TextView
+import de.grobox.transportr.trips.BaseViewHolder
 import de.grobox.transportr.utils.TransportrUtils.getLocationName
 import de.schildbach.pte.dto.Stop
 import kotlinx.android.synthetic.main.list_item_stop.view.*
 
 
-internal class StopViewHolder(v: View, listener: LegClickListener) : BaseViewHolder(v, listener) {
+internal class StopViewHolder(v: View, val listener : LegClickListener) : BaseViewHolder(v) {
```
Comment (grote) [inline app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt]: Could the listener be `private`?

File: app/src/main/java/de/grobox/transportr/trips/detail/LegViewHolder.kt [hunk 4]
```diff
@@ -45,7 +46,7 @@ import de.schildbach.pte.dto.Trip.*
 import kotlinx.android.synthetic.main.list_item_leg.view.*
 
 
-internal class LegViewHolder(v: View, listener: LegClickListener, private val showLineName: Boolean) : BaseViewHolder(v, listener) {
+internal class LegViewHolder(v: View, protected val listener: LegClickListener, private val showLineName: Boolean) : BaseViewHolder(v) {
```
Comment (grote) [inline app/src/main/java/de/grobox/transportr/trips/detail/LegViewHolder.kt]: Could the listener be `private`?

File: app/src/main/java/de/grobox/transportr/trips/search/TripViewHolder.kt [hunk 5]
```diff
@@ -36,39 +36,29 @@ import de.schildbach.pte.dto.Trip
...
 
     fun bind(trip: Trip, listener: OnTripClickListener) {
         // Relative Departure Time
         setRelativeDepartureTime(fromTimeRel, trip.firstDepartureTime)
 
-        // Departure Time
+        // Departure Time and Delay
         val firstLeg = trip.legs[0]
         if (firstLeg is Public) {
-            fromTime.text = getTime(context, firstLeg.getDepartureTime(true))
```
Comment (grote) [inline app/src/main/java/de/grobox/transportr/trips/search/TripViewHolder.kt]: Did you check that what we do in `setDepartureTimes()` is equivalent to what happens in `firstLeg.getDepartureTime(true)`?

File: app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt (hunk 2 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt]: Up to now, the green `+0` is only shown in the trip details view, not in the search results view (if real time information is available, obviously). So I have added this flag to be able to differentiate between the two cases. But if you want to change the app's behavior here, it would be easy to adopt.

File: app/src/main/java/de/grobox/transportr/trips/search/TripViewHolder.kt (hunk 5 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/trips/search/TripViewHolder.kt]: It is equivalent to what happened before in this line and in lines 66-71.

File: app/src/main/java/de/grobox/transportr/utils/DateUtils.java (hunk 1 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/utils/DateUtils.java]: True, I have removed the annotation, but the only two usages were not handling the `null` case anyway (as I have been changing them within this PR).

File: app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt (hunk 3 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt]: Indeed, I have changed it.

File: app/src/main/java/de/grobox/transportr/trips/detail/LegViewHolder.kt (hunk 4 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/trips/detail/LegViewHolder.kt]: Indeed, I have changed it.

**Comment by ialokim** [comment]
Thanks a lot for your review! Do you want me to add another commit applying the three (little) changes or do you prefer rebasing and force-pushing for cleaner git history?

File: app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt (hunk 2 above)
Comment (grote) [reply app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt]: I think we should indicate the availability of real-time information everywhere consistently. So we could drop the flag, right?

**Comment by grote** [comment]
Thanks for the fixes! Would be nice to force push all three commits into a single one.

File: app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt (hunk 2 above)
Comment (ialokim) [reply app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt]: So then yes, the flag can be dropped.

**Comment by ialokim** [comment]
> Would be nice to force push all three commits into a single one.

Okay, done. I have applied all the changes and force-pushed the new version.

**Comment by grote** [comment]
Awesome, thanks!
